export const personalInfo = {
  name: "David Ospina",
  location: "Bogotá, Colombia",
  email: "davidospinainfo@gmail.com",
  github: "https://github.com/DaveOzz14",
  linkedin: "https://www.linkedin.com/in/davidospinat/",
};

export const workExperience = [
  {
    company: "Choucair Testing",
    location: "Bogotá, Colombia",
    position: "Digital Performance Manager",
    period: "Agosto 2024 - Actual",
    achievements: [
        "Product Owner. Responsable de diseñar, implementar y gestionar la estrategia de producto de observabilidad en la organización, asegurando que los sistemas y aplicaciones sean monitorizados, ",
        "analizados y optimizados para garantizar su rendimiento, disponibilidad y fiabilidad. Este rol requiere",
        "una combinación de habilidades técnicas, liderazgo y visión estratégica para alinear las iniciativas",
        "de observabilidad con los objetivos del negocio.",
        "Colaborar con otros líderes técnicos y de negocio para alinear las iniciativas de observabilidad con",
        "los objetivos empresariales.",
        "Diseño e Implementación: Diseñar e implementar soluciones de observabilidad que incluyan",
        "métricas, logs, trazas y monitoreo de usuarios.",
        "Desarrollar un modelo de Observabilidad basado en el entendimiento de la Arquitectura de los",
        "clientes. Equipo liderado: 5 Personas (Analistas de Observabilidad, UX, Desarrolladores)",
        
        "Logros:",
        "Diseño de Producto DPM: Lideré el diseño e implementación de capacidades Digital Performance",
        "Management (DPM), alineando productos y servicios con los objetivos de negocio de los clientes.",
        "Implementé estrategias para reducir fricciones de usuario, mejorar la experiencia digital y fortalecer la",
        "observabilidad en la causa raíz de problemas en flujos transaccionales, diseño de estrategia comercial,",
        "pricing, diseño de propuestas comerciales, speaker de eventos sobre el producto.",
        
        "Plataforma DPM: Dirigí el desarrollo e implementación de una plataforma propia de Digital Performance",
        "Management (DPM) para la empresa, proporcionando visibilidad y control en flujos de negocio mediante",
        "herramientas avanzadas de APM y DEM. La solución fue construida con Python y OpenTelemetry,",
        "mejorando la capacidad de análisis y monitoreo de procesos críticos",
    ],
  },
  {
    company: "Fundación Universitaria Internacional de la Rioja",
    location: "Bogotá, Colombia",
    position: "Responsable de Equipo de Inteligencia Artificial",
    period: "Marzo 2024 - Julio 2024",
    achievements: [
      "Jefe de Equipo (6 personas) del Departamento de Inteligencia Artificial en Colombia.Lideré la gestión de proyectos de IA en la Universidad, optimizando el desarrollo de soluciones",
      "innovadora.Comunicación directa con el director de IA de la Universidad en España, para seguimiento de actividades, porcentaje de avances, gestión de equipos.",
      "Liderazgo técnico de los procesos de desarrollo de IA.",
      "Modelos Chatgpt 3.5 y 4.",
      "Herramientas LLM PromptFlow, LangChain, LlamaIndex, Python, pyndentic, sqlmodel, langchain, RAG.",
      "RPG y RPA",
      "Planeación de procesos de innovación tecnológica en la Universidad",
      "Transformación digital.",
      "Logros:",
      "Proyecto de Generación de Contenidos con IA: Lideré el desarrollo de modelos de Inteligencia Artificial",
      "Generativa para la creación automatizada de contenidos educativos. Implementé agentes de IA capaces",
      "de transformar textos en lenguaje natural en documentos estructurados para cursos universitarios,",
      "optimizando la producción de material académico.",
      "Proyecto de Transcripción de Llamadas con IA: Implementé modelos de procesamiento de lenguaje",
      "natural (NLP) para la transcripción automática de llamadas telefónicas y la extracción de información",
      "clave para áreas de mercadeo, servicio al cliente y educación. La solución mejoró la eficiencia operativa",
      "y la toma de decisiones basada en datos.",
      "Chatbot con IA Generativa: Diseñé y desarrollé un Chatbot con IA Generativa utilizando RAG y Web",
      "Scraping para responder preguntas frecuentes en el sitio web becta.online. La implementación mejoró la",
      "experiencia del usuario, optimizando la resolución de consultas y reduciendo la carga operativa del",
      "servicio al cliente.",
      "Motivo Retiro: Finalización del contrato fijo a 6 meses.",
      
    ],
  },
  {
    company: "Bision Consulting",
    location: "Bogotá, Colombia",
    position: "Gerente Proyectos",
    period: "Septiembre 2023 - Enero 2024",
    achievements: [
      "Gerente de Proyectos BI y Analítica de datos (ETL - Datamarts Facts/Dimensiones- Power BI/Cognos),Control Financiero de proyecto (Indicadores).",
        "Gestión de Talento Humano asignado a los proyectos (BackEnd, FrontEnd, Analistas de Negocio, líder técnico)",
        "Control Alcance, Tiempo, Costos",
        "Gestión Proyectos Ciclo Predictivo (Inicio-Planeación-Ejecución-Monitoreo-Cierre)",
        "Proyectos Híbridos Cascada-Ágil. Gestión Equipo de Desarrollo y Data.",
        "Captura, Diseño, gestión y control de Requerimientos.",
        "Logros:",
        "Proyecto de Datos en el Sector Financiero (FINAGRO): Lideré el diseño e implementación de un",
        "sistema de analítica de datos para la gerencia de riesgos (mercado, liquidez, garantías y crédito). Un",
        "Data Warehouse con procesos ETL e ingesta de datos, permitiendo la integración y análisis de grandes",
        "volúmenes de información. La solución, conectada a Power BI, optimizó la visualización de datos",
        "estratégicos y mejoró la toma de decisiones en riesgos financieros.",
        "Proyecto de Primas de Seguros de Vida y Autos (Mapfre Colombia y Ecuador): Dirigí la",
        "implementación de un sistema de análisis y gestión de primas de seguros, optimizando la",
        "administración y control de pólizas en los segmentos de vida y automóviles.",
        "Motivo Retiro: Finalización con éxito del proyecto Principal FINAGRO, retiro voluntario",
    ],
  },

  {
    company: "Consejo Noruego para Refugiados",
    location: "Bogotá, Colombia",
    position: "Coordinador ICT",
    period: "Octubre 2019 - Enero 2023",
    achievements: [
      "Coordinador de proyectos IT (Proyectos-Diseño de Arquitecturas basado en RequerimientosPlaneación- Tiempos Costos Riesgos), Gerencia TI: 1 año (Control Equipos de Trabajo en cada",
        "proyecto)",
        "Implementación de Arquitectura de Software Cloud.",
        "Creación control y Monitoreo de Balance Score Card",
        "Diseño,Control y manejo de presupuesto mayor a 300 mil USD Gestión proyectos Software con Scrum/Kanban Azure Boards. Gestión de proyectos de Tecnología y Telecomunicaciones",
        "Proyectos Internacionales en Salesforce CRM(Apex,Lightning,VisualForce)",
        "Gestión Proyectos transformación digital (Kioskos Digitales, Chatbots, Inteligencia Artificial, Call Center",
        "Cloud Twilio, Aplicaciones Mobiles Android, Landing Page, integraciones Api Rest) –",
        "Brainstorming, Priorización de ideas, StoryBoard, Role Playing (Team: Diseñadores, FrontEnd,",
        "BackEnd, DataBases) en toda Latinoamérica para mejora de Experiencia de usuario de los productos NRC.",
        "Diseño UI, Inteligencia de Negocios Data Analitycs en Power BI.",
        "Planeación de desarrollo de software interno y con proveedores. Bussines Intelligence Power BI",
        "ETL Servidores Cloud Azure y AWS Power Platform Power Apps, Power Automate, Power Virtual",
        "Agent, Power Bi, Sharepoint, proyectos de Desarrollo Low Code",
        "Proyectos TIC mediante metodología Scrum y Kanban. Trello, Planner, Project,Git,ScrumDo,Azure",
        "Gestión proyectos de software Java,SpringBoot, Hibernate, AWS",
        "Logros:",
        "Proyecto Horus – Sistema de Gestión de Misiones Humanitarias: Diseñé e implementé un sistema",
        "de gestión de misiones humanitarias, optimizando la planificación, seguimiento y ejecución de",
        "operaciones en campo. La solución permitió mejorar la gestión de recursos y la coordinación de",
        "equipos en entornos de crisis.",
        "Proyecto Omnicanal para Atención a Usuarios: Lideré el desarrollo de un sistema omnicanal,",
        "integrando Contact Center, Kioskos Digitales, Chatbots y Aplicaciones Móviles. La solución mejoró",
        "la experiencia del usuario y optimizó la interacción en múltiples canales de atención.",
        "Proyecto Educativo Educarural – Colegio Virtual: Implementé una plataforma de educación digital",
        "para niños en zonas de baja o nula conectividad, garantizando acceso a contenidos educativos",
        "mediante soluciones offline y optimización del acceso remoto.",
        "Liderazgo del Área TIC en Latinoamérica: Gestioné equipos técnicos en varios países de la región,",
        "asegurando la implementación de estrategias tecnológicas alineadas con los objetivos",
        "organizacionales.",
        "Reducción de Tiempos en Mesa de Ayuda (-40%): Implementé mejoras en la gestión de tickets y",
        "automatización de respuestas, reduciendo en 40% el tiempo de respuesta y optimizando la eficiencia",
        "del soporte técnico.",
        "Motivo Retiro: Fin del ciclo en la compañía, renuncia voluntaria.",
    ],
  },
   {
    company: "VASS",
    location: "Bogotá, Colombia",
    position: "Consultor Salesforce",
    period: "Junio 2019 - Septiembre 2019",
    achievements: [
      "Consultor CRM Salesforce Proyecto TIGO Millicom Latino América. Análisis de Requerimientos de Negocio con el cliente Análisis y Mejoramiento de",
      "Procesos de Software",
      "Lightning Experience , Apex, Force.com, Flow, Trigger.",
      "Administración Salesforce",
      "Logros:",
      "Proyecto TIGO Millicom – Sistema de Gestión de Ventas: Lideré el desarrollo e implementación de un Sistema de Gestión", 
      "de Ventas para TIGO Millicom, optimizando la administración y seguimiento del ciclo deventas de productos y servicios.", 
       "Integré Salesforce CRM con módulos avanzados de automatización de procesos, análisis de datos y generación de reportes, mejorando la eficiencia operativa y la toma de decisiones estratégicas.",
      "Motivo Retiro: Nueva oportunidad laboral para dirigir proyectos a nivel Latino América, Retiro Voluntario.",

    ],
  },

     {
    company: "Credifamilia",
    location: "Bogotá, Colombia",
    position: "Salesforce Senior",
    period: "Marzo 2019 - Junio 2019",
    achievements: [
      "Proyectos Fintech en productos Hipotecarios, CDT digital, Consumo, Retanqueo, gestionando diferentes proyectos que se desarrollan sobre el CRM Salesforce.",
      "Apex, Flow, Carga de Datos, Integración de Datos con Sistema CORE Financiero, Triggers, Sales Cloud, Service Cloud",
      "Logros:",
      "Proyecto CDT Digital – Integración Web y Salesforce CRM: Diseñé e implementé la integración de un portal web transaccional con Salesforce CRM, optimizando la gestión y contratación de Certificados de Depósito a Término (CDT). La solución permitió la automatización de procesos, mejorando la experiencia del usuario, la seguridad en las transacciones y la eficiencia operativa en la gestión financiera.",
      "Motivo Retiro: Nueva oportunidad laboral para dirigir proyecto de Telecomunicaciones, Retiro Voluntario",

    ],
  },

  
     {
    company: "Fundación Neumologica Colombiana",
    location: "Bogotá, Colombia",
    position: "Salesforce Senior",
    period: "Junio 2017 - Enero 2019",
    achievements: [
      "Gestión del Framework Scrum para los proyectos del Dpto de Sistemas, Facilitar reuniones, evangelizar la metodología, control de Historias, Backlog, SprintPlanning, Review, Restrospective.",
      "Scrum Team 4 Personas.",
      "CRM Salesforce (Apex, VisualForce), Administración de Plataforma, integración de ERP-CRM",
      "Desarrollo Software Medico para el Agendamiento Citas, historia Clínica.",
      "Logros:",
      "Implementación del Sistema INSPIRA – Citas Médicas e Integración con ERP Servinte.",
      "Lideré la implementación del Sistema INSPIRA, desarrollando módulos especializados para la gestión de citas médicas e integrándolos con el ERP Servinte. La solución automatizó la asignación de turnos, optimizó la administración de agendas médicas y mejoró la interoperabilidad entre sistemas, aumentando la eficiencia operativa y la experiencia del paciente.",
      "Motivo Retiro: Ciclo Finalizado con la compañía, búsqueda de nuevos retos, retiro Voluntario",

    ],
  },


      {
    company: "Asopagos",
    location: "Bogotá, Colombia",
    position: "Desarrollador FullStack",
    period: "Junio 2016 - Mayo 2017",
    achievements: [
      "Software Developer Plataforma PILA JAVA JEE JSP JSF PRIMEFACES Postgresql, JBOSS eap 6.3",
      "Desarrollo de Resoluciones.",
      "Manejo y solución de incidencias en Producción.",
      "Análisis de Requerimientos Funcionales.",
      "Software Developer Plataforma Facturación Electrónica JAVA JEE JSF PRIMEFACES. Desarrollo de Web Services Soap Spring.",
      "Despliegue e implementación de Software Corporativo.",
      "Pruebas Unitarias.",
      "Documentación de Aplicaciones y Desarrollos.",
      "Logros: Implementación de Resolución del Ministerio de Salud en cuanto a los cambios realizados para los pagos de Seguridad Social en 2016.",
      "Motivo Retiro: Ciclo Finalizado con la compañía, la idea era buscar nuevos horizontes laborales con oportunidades de crecimiento, Retiro Voluntario.",


    ],
  },

       {
    company: "Expreso Viajes y Turismo CAFAM",
    location: "Bogotá, Colombia",
    position: "Analista Senior",
    period: "Octubre 2012 - Diciembre 2015",
    achievements: [
      "Gestión de proyectos de Tecnología de Agencia de Viajes Cafam",
      "Liderazgo del Departamento de Tecnología.",
      "Proyectos Desarrollo de Software Team Dev 3 Personas, Sprint, BackLog y Sprint Planning.",
      "Proyectos de Interacción por medio de interfaces entre ERP local y Sistema GDS Sabre.",
      "Proyectos en Sistema Global de Tiquetes Aéreos Sabre QIK Sabre Red Avanzado para la Agencia de Viajes en Colombia.",
      "DBA Sybase MT Monitoreo y Análisis de Procesos DB",
      "Diseño de Bases de Datos Relacionales",
      "Diseño y construcción de procedimientos Almacenados",
      "Análisis y desarrollo de Software ERP en lenguaje Power Builder 12.5,",
      "Administración general del Departamento de TI mediante guía de Servicios ITIL",
      "Administración de personal Soporte Software primer nivel.",
      "Análisis de Requerimientos Funcionales, tiempos, riesgos, costos, interesados.",
      "Despliegue e implementación de Software Corporativo.",
      "Pruebas Unitarias.",
      "Documentación de Aplicaciones y Desarrollos",
      "Gestión proyectos de software Java,Primefaces, Hibernate",
      "Logros:",
      "Integración de Pasarela de Pagos y Sistema de Reservas Sabre | Migración ERP Ulisse a ERP Zeus:Lideré la integración de una pasarela de pagos con el Sistema de Reservas Aéreas Sabre, optimizando la gestión de transacciones y reservas en tiempo real.", 
      "Coordiné la migración del ERP Ulisse a ERP Zeus, asegurando la correcta transferencia y consolidación del histórico de datos contables mediante un proceso minutograma estructurado, garantizando la integridad y disponibilidad de la información en el ambiente productivo.",
      "Motivo Retiro: Ciclo Finalizado con la compañía, la idea era buscar nuevos horizontes laborales con oportunidades de crecimiento, Retiro Voluntario",


    ],
  },

  
       {
    company: "Corparques Mundo Aventura",
    location: "Bogotá, Colombia",
    position: "Desarrollador FullStack",
    period: "Febrero 2010 - Agosto 2012",
    achievements: [
      "El desarrollo de software se implementaba con metodología Scrum, donde se evangelizaba al grupo de trabajo sobre el framework, BackLog, SprintPlanning, seguimiento y control de historias, mi trabajo con el producto Owner se enfocaba a la gestión de los proyectos, control, calidad y despliegue de los desarrollos de la empresa.",
      "Desarrollo de Software en Lenguaje de Programación Java J2E en implementación de proyecto ERP bajo Multi S.O",
      "Desarrollo de Software Web para plataformas de Producto, Web Site Corporativo incluyendo E-Commerce y nuevas tendencias de tecnología basados en lenguaje de Programación PHP.",
      "DBA Sybase MT en monitoreo de Procesos.",
      "Logros:",
      "Implementación del Proceso FAN y Sistema para el Restaurante Arazá: Lideré la implementación del Proceso FAN en Mundo Aventura, optimizando la gestión de clientes y la fidelización a través de soluciones tecnológicas. Además, desarrollé e implementé un sistema de gestión para el Restaurante Arazá, automatizando los procesos operativos, administrativos y de facturación, mejorando la eficiencia y la experiencia del cliente.",
      "Motivo Retiro: Ciclo Finalizado con la compañía, la idea era buscar nuevos horizontes laborales con oportunidades de crecimiento, Retiro Voluntario.",

    ],
  },
];

export const education = [
  {
    institution: "International MBA Institute",
    location: "Remote",
    degree: "MBA Business Administration",
    period: "2022 - 2023",
    /*achievements: [
      "President of the Department of Information Technology",
      "G20 student delegate",
      "Organized multiple technical workshops and events",
      "Represented my college in multiple national and international hackathons and won.",
    ],*/
  },
   {
    institution: "Politécnico Gran Colombiano",
    location: "Bogotá",
    degree: "Especialización Gerencia Proyectos e Inteligencia de Negocios",
    period: "2018 - 2019",
    /*achievements: [
      "President of the Department of Information Technology",
      "G20 student delegate",
      "Organized multiple technical workshops and events",
      "Represented my college in multiple national and international hackathons and won.",
    ],*/
  },
   {
    institution: "Universidad San Martin",
    location: "Bogotá",
    degree: "Ingeniero de Sistemas",
    period: "2007 - 2017",
    /*achievements: [
      "President of the Department of Information Technology",
      "G20 student delegate",
      "Organized multiple technical workshops and events",
      "Represented my college in multiple national and international hackathons and won.",
    ],*/
  },
];
export const skills = {
  programmingLanguages: [
    "Java: PrimeFaces, Spring, Maven, JPA, Hibernate",
    "JavaScript",
    "Python: Django (Flask, FastAPI,Pandas, Pydantic)",
    "C++",
    "React",
    "Node",
    "RabbitMQ",
    "CQRS",
    "Kotlin",
    "Salesforce",
    "Wordpress",
    "Angular",
    "Dynatrace",
    "DataDog",
    "Opentelemetry",
    "Power Apps",
    "Power Automate",
  
  ],
  frontendDevelopment: [
    "NLP",
    "Python",
    "SQL Model",
    "Prompt Flow",
    "LangChain",
    "RAG",
    "n8n",
  ],
  backendDevelopment: ["Scrum", "Kanban","Six Sigma"," Product Owner","Design Thinking","PMI","Gestión de Proyectos inicio-fin, (costos, tiempos, riesgos, cambios, alcance)"," Creación y Gestión de presupuestos de TIC hasta de 400K USD","Gestión de Proyectos hasta 900M COP, planeación estratégica tecnologías Información PETI","Balance ScoreCard , Análisis de requerimientos, Product Backlog","Reporte y seguimiento con altas gerencias y cargos gerenciales","Transformación digital, gestión de proyectos con Jira, Trello, Project, Kanban, Azure Boards, Miro"],
  databaseAndStorage: ["PostgreSQL", "SQL","MySQL","Oracle","Neo4J"],
  cloudAndDevOps: ["AWS","Azure"],
  toolsAndServices: [
    "Arquitectura: MVP, MicroServicios, DOD, CQRS",
    "ETL y DataWareHouse",
    "Power BI",
    "RESTful APIs",
    "Servidores de Aplicaciones: Glassfish, Jboss, Tomcat, Apache",
    "Docker",
    "Kubernetes",
  ],
};

export const projects = [
  {
    title: "Creador de cuentos con IA",
    github: "https://github.com/DaveOzz14/IA_Creador_Cuentos",
    description: [
    "Generador de Texto con LMStudio y DeepSeek LLM Este es un proyecto simple en Python que utiliza LMStudio y el modelo deepseek-r1-distill-llama-8b para generar texto a partir de un prompt.",
    "🚀 Requisitos",
    "Python 3.8+",
    "LMStudio instalado y ejecutándose localmente",
    "Modelo deepseek-r1-distill-llama-8b cargado en LMStudio",
    ],
  },
  {
    title: "Portal Pacientes Web",
    github: "https://github.com/DaveOzz14/IA_Creador_Cuentos",
    description: [
      "Portal Web creado para que paciente de la clinica puedan solicitar citas, validar examenes, controlar su historial medico.",
    ],
  },
];

export const awards = [
  {
    name: "Scrum Master",
    issuer: "Agilismo",
    date: "2017",
    type: "International",
    position: "Gestion de proyectos",
  },
  {
    name: "Product Owner",
    issuer: "Agilismo",
    date: "2019",
    type: "International",
    position: "Gestion de proyectos",
  },
  {
    name: "Kanban",
    issuer: "Agilismo",
    date: "2019",
    type: "Internartional",
    position: "Gestion de proyectos",
  },
  {
    name: "Six Sigma YB",
    issuer: "Lean",
    date: "2018",
    type: "International",
    position: "Gestion de Procesos",
  },
  {
    name: "Business Intelligence",
    issuer: "BI",
    date: "2020",
    type: "International",
    position: "Analitica",
  },
  {
    name: "DevOps",
    issuer: "Tecnologia",
    date: "2018",
    type: "International",
    position: "Integracion Continua",
  },
  {
    name: " Design Thinking Fundamentals",
    issuer: "Procesos",
    date: "2019",
    type: "International",
    position: "Gestion de Procesos",
  },
  {
    name: "Project Manager IO4PM",
    issuer: "Proyectos",
    date: "2024",
    type: "International",
    position: "Gestion de Proyectos",
  },
   {
    name: "Neo4J",
    issuer: "Tecnologia",
    date: "2025",
    type: "International",
    position: "Bases de Datos",
  },
];
